#!/bin/sh
#
#
# Copyright © 2020 Portworx
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

function usage() {
    echo "
Create a StorageCluster for the Portworx Operator

Usage:
  pxc operator cluster create [flags]

Flags:
  -h, --help        help for create
  --name            Name of cluster
  --csi             Use CSI
"
  exit 1
}

parsed=$(getopt -o h -n "pxc operator cluster create" --long name:,help,csi -- "$@" )
if [ $? -ne 0 ] ; then
    usage
fi

eval set -- "$parsed"

NAME=""
CSI=false

while true; do
    case "$1" in
        --csi) CSI=true; shift ;;
        --name) NAME="$2"; shift 2 ;;
        -h | --help) usage;;
        --) shift; break ;;
        *) usage; break ;;
    esac
done

if [ "$NAME" = "" ] ; then
    echo "Must provide a name"
    exit 1
fi

NAME=$(echo $NAME | sed "s# #-#g")

curl -sL https://install.portworx.com/?operator=true\&csi=${CSI}\&c=${NAME}

