#!/bin/bash
#
# Copyright © 2020 Portworx
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Helps connect to a node host through the kubernetes pod
#


if [ $# -ne 1 ] ; then
	echo "Must provide a node name"
	exit 1
fi

node=$1
pod=$(kubectl -n kube-system get pods -l name=portworx -o wide | grep "${node}" | awk -P '{print $1}')
kubectl -n kube-system exec -c portworx -ti $pod /bin/bash
