#!/bin/bash
#
#
# Copyright © 2020 Portworx
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Runs pxctl commands on the host
#

required="kubectl kubectl-pxc"

for req in $required ; do
	if ! which $req > /dev/null 2>&1 ; then
		echo "$req is required"
		exit
	fi
done


if [ "$1" = "-n" ] ; then
	NODE=$2
	shift 2
else
	k8snodes=$(kubectl get pod -n ${PXC_PORTWORX_SERVICE_NAMESPACE} -lname=portworx -o jsonpath='{.items[*].spec.nodeName}')
	pxnodes=$(kubectl pxc node list -o json | jq -r '.[].hostname')
	# Find all nodes common to both $k8snodes and $pxnodes
	nodes=$(comm -12 <(echo $pxnodes | tr ' ' '\n' | sort) <(echo $k8snodes | tr ' ' '\n' | sort))
	for node in $nodes ; do
		status=$(kubectl pxc node get $node -o json | jq -r '.[].status')
		if [ $status -eq 2 ] ; then
			NODE=$node
			break 1
		fi
	done
fi

if [ -z "$NODE" ] ; then
	echo "Unable to find node that is online"
	exit 1
fi

echo ">> Running pxctl on $NODE"
pod=$(kubectl -n ${PXC_PORTWORX_SERVICE_NAMESPACE} get pods -l name=portworx -o wide | grep "${NODE}" | awk '{print $1}')
kubectl -n ${PXC_PORTWORX_SERVICE_NAMESPACE} exec -ti $pod -c portworx -- /bin/sh -c "PXCTL_AUTH_TOKEN=${PXC_TOKEN} /opt/pwx/bin/pxctl $*"
